"""initial

Revision ID: 1134ebbfcab0
Revises: 
Create Date: 2026-02-06 12:52:43.945307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1134ebbfcab0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('profile_url', sa.String(length=512), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('worker_heartbeats',
    sa.Column('worker_name', sa.String(length=255), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_name')
    )
    op.create_table('videos',
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('shortcode', sa.String(length=50), nullable=False),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(length=1024), nullable=True),
    sa.Column('audio_file_path', sa.String(length=1024), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcode'),
    sa.UniqueConstraint('video_id')
    )
    op.create_index('account_published_idx', 'videos', ['account_id', 'published_at'], unique=False)
    op.create_table('metric_schedules',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('status_scheduled_idx', 'metric_schedules', ['status', 'scheduled_at'], unique=False)
    op.create_index('video_schedule_idx', 'metric_schedules', ['video_id', 'scheduled_at'], unique=False)
    op.create_table('metrics',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('video_measured_idx', 'metrics', ['video_id', 'measured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('video_measured_idx', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('video_schedule_idx', table_name='metric_schedules')
    op.drop_index('status_scheduled_idx', table_name='metric_schedules')
    op.drop_table('metric_schedules')
    op.drop_index('account_published_idx', table_name='videos')
    op.drop_table('videos')
    op.drop_table('worker_heartbeats')
    op.drop_table('accounts')
    # ### end Alembic commands ###
