"""add metric_schedules table

Revision ID: 284ae8b6c888
Revises: 57a9647a16b9
Create Date: 2026-01-29 21:41:04.324381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284ae8b6c888'
down_revision: Union[str, Sequence[str], None] = '57a9647a16b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_schedules',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('status_scheduled_idx', 'metric_schedules', ['status', 'scheduled_at'], unique=False)
    op.create_index('video_schedule_idx', 'metric_schedules', ['video_id', 'scheduled_at'], unique=False)
    op.drop_index('ix_accounts_id', table_name='accounts')
    op.drop_index('ix_metrics_id', table_name='metrics')
    op.drop_index('ix_videos_id', table_name='videos')
    op.drop_index('ix_videos_shortcode', table_name='videos')
    op.drop_index('ix_videos_video_id', table_name='videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_videos_video_id', 'videos', ['video_id'], unique=True)
    op.create_index('ix_videos_shortcode', 'videos', ['shortcode'], unique=True)
    op.create_index('ix_videos_id', 'videos', ['id'], unique=False)
    op.create_index('ix_metrics_id', 'metrics', ['id'], unique=False)
    op.create_index('ix_accounts_id', 'accounts', ['id'], unique=False)
    op.drop_index('video_schedule_idx', table_name='metric_schedules')
    op.drop_index('status_scheduled_idx', table_name='metric_schedules')
    op.drop_table('metric_schedules')
    # ### end Alembic commands ###
